/* ============================================================
   build.js — Generates js/firebase-config.js from Vercel
   environment variables at deploy time.
   Run: node build.js
   ============================================================ */

const fs = require('fs');

const {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
} = process.env;

/* Validate all required vars are present */
const missing = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
].filter(k => !process.env[k]);

if (missing.length) {
  console.error('❌ Missing environment variables:', missing.join(', '));
  process.exit(1);
}

const content = `/* AUTO-GENERATED by build.js — do not edit manually */
const firebaseConfig = {
  apiKey:            "${FIREBASE_API_KEY}",
  authDomain:        "${FIREBASE_AUTH_DOMAIN}",
  projectId:         "${FIREBASE_PROJECT_ID}",
  storageBucket:     "${FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
  appId:             "${FIREBASE_APP_ID}",
  measurementId:     "${FIREBASE_MEASUREMENT_ID || ''}",
};

firebase.initializeApp(firebaseConfig);

const FDB   = firebase.firestore();
const FAUTH = firebase.auth();

FDB.enablePersistence({ synchronizeTabs: true }).catch(() => {});

window.FDB   = FDB;
window.FAUTH = FAUTH;
`;

fs.mkdirSync('js', { recursive: true });
fs.writeFileSync('js/firebase-config.js', content, 'utf8');
console.log('✅ js/firebase-config.js generated successfully');
